{ name = "snapshots"
, dependencies =
  [ "arrays"
  , "bifunctors"
  , "console"
  , "const"
  , "contravariant"
  , "convertable-options"
  , "effect"
  , "either"
  , "enums"
  , "exists"
  , "foldable-traversable"
  , "functions"
  , "heterogeneous"
  , "identity"
  , "integers"
  , "lists"
  , "maybe"
  , "partial"
  , "prelude"
  , "profunctor-lenses"
  , "random"
  , "record"
  , "refs"
  , "safe-coerce"
  , "strings"
  , "transformers"
  , "tuples"
  , "type-equality"
  , "variant"
  ]
, packages = ../../../packages.dhall
, sources = [ "./*.purs", "./*/*.purs" ]
}
