{ name = "snapshots"
, dependencies =
  [ "arrays"
  , "console"
  , "convertable-options"
  , "effect"
  , "either"
  , "exists"
  , "foldable-traversable"
  , "foreign-object"
  , "functions"
  , "heterogeneous"
  , "identity"
  , "integers"
  , "lists"
  , "maybe"
  , "partial"
  , "prelude"
  , "profunctor-lenses"
  , "record"
  , "refs"
  , "safe-coerce"
  , "st"
  , "strings"
  , "tuples"
  , "type-equality"
  , "unsafe-coerce"
  , "variant"
  ]
, packages = ../../../packages.dhall
, sources = [ "./*.purs", "./*/*.purs" ]
}
