import * as $runtime from "../runtime.js";
import * as Data$dConst from "../Data.Const/index.js";
import * as Data$dEuclideanRing from "../Data.EuclideanRing/index.js";
import * as Data$dMonoid from "../Data.Monoid/index.js";
import * as Data$dOrd from "../Data.Ord/index.js";
const test9 = "";
const test8 = "hi";
const test7 = "h";
const test6 = -2147483648;
const test5 = 2147483647;
const test4 = /* #__PURE__ */ (() => Data$dOrd.ordString.compare("h")("i"))();
const test3 = true;
const test21 = /* #__PURE__ */ (() => Data$dConst.applicativeConst(Data$dMonoid.monoidString).pure(1))();
const test20 = "hi";
const test2 = false;
const test19 = 1;
const test18 = false;
const test17 = true;
const test16 = /* #__PURE__ */ Data$dEuclideanRing.intMod(2)(2);
const test15 = /* #__PURE__ */ Data$dEuclideanRing.intDiv(1)(1);
const test14 = 1;
const test13 = 0;
const test12 = 1;
const test11 = 0;
const test10 = 2;
const test1 = false;
export {test1, test10, test11, test12, test13, test14, test15, test16, test17, test18, test19, test2, test20, test21, test3, test4, test5, test6, test7, test8, test9};
